[workspace]
members = ["password_crack", "app", "file-password-finder"]
default-members = ["password_crack"]

[profile.release]
opt-level = 'z'
strip = true
lto = true
codegen-units = 1
panic = "abort"

[profile.dev.package."*"]
opt-level = 2
