[package]
name = "zip-password-finder"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# 性能比官方的强，所以选择它 
crossbeam-channel = "0.5.6" 
zip = "0.6.2"
