[workspace]
members = ["password_crack", "app", "file-password-finder"]
default-members = ["file-password-finder"]

[profile.release]
opt-level = 'z'
strip = true
lto = true
codegen-units = 1
panic = "abort"
